/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as docsFaqRouteImport } from './routes/(docs)/faq'
import { Route as docsGuideRouteImport } from './routes/(docs)/guide'
import { Route as docsPrivacyRouteImport } from './routes/(docs)/privacy'
import { Route as docsTermsRouteImport } from './routes/(docs)/terms'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as BoardIndexRouteImport } from './routes/board/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const docsFaqRoute = docsFaqRouteImport.update({
  id: '/(docs)/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const docsGuideRoute = docsGuideRouteImport.update({
  id: '/(docs)/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const docsPrivacyRoute = docsPrivacyRouteImport.update({
  id: '/(docs)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const docsTermsRoute = docsTermsRouteImport.update({
  id: '/(docs)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/(landing)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIndexRoute = BoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/faq': typeof docsFaqRoute
  '/guide': typeof docsGuideRoute
  '/privacy': typeof docsPrivacyRoute
  '/terms': typeof docsTermsRoute
  '/': typeof landingIndexRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/faq': typeof docsFaqRoute
  '/guide': typeof docsGuideRoute
  '/privacy': typeof docsPrivacyRoute
  '/terms': typeof docsTermsRoute
  '/': typeof landingIndexRoute
  '/board': typeof BoardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/(docs)/faq': typeof docsFaqRoute
  '/(docs)/guide': typeof docsGuideRoute
  '/(docs)/privacy': typeof docsPrivacyRoute
  '/(docs)/terms': typeof docsTermsRoute
  '/(landing)/': typeof landingIndexRoute
  '/board/': typeof BoardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/login' | '/faq' | '/guide' | '/privacy' | '/terms' | '/' | '/board/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/faq' | '/guide' | '/privacy' | '/terms' | '/' | '/board'
  id:
    | '__root__'
    | '/login'
    | '/(docs)/faq'
    | '/(docs)/guide'
    | '/(docs)/privacy'
    | '/(docs)/terms'
    | '/(landing)/'
    | '/board/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  docsFaqRoute: typeof docsFaqRoute
  docsGuideRoute: typeof docsGuideRoute
  docsPrivacyRoute: typeof docsPrivacyRoute
  docsTermsRoute: typeof docsTermsRoute
  landingIndexRoute: typeof landingIndexRoute
  BoardIndexRoute: typeof BoardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/faq': {
      id: '/(docs)/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof docsFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/guide': {
      id: '/(docs)/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof docsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/privacy': {
      id: '/(docs)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof docsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(docs)/terms': {
      id: '/(docs)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof docsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/': {
      id: '/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof BoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  docsFaqRoute: docsFaqRoute,
  docsGuideRoute: docsGuideRoute,
  docsPrivacyRoute: docsPrivacyRoute,
  docsTermsRoute: docsTermsRoute,
  landingIndexRoute: landingIndexRoute,
  BoardIndexRoute: BoardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
